-- Yeni görevleri ekle
INSERT INTO tasks (taskname, taskicon) VALUES
('Güne erken başla', '🌅'),
('Kahvaltı yap', '🍳'),
('Vitaminlerini al', '💊'),
('20 dakika yürüyüş yap', '🚶‍♂️'),
('Meyve ye', '🍎'),
('Ev bitkilerini sula', '🌿'),
('Ailenle konuş', '👨‍👩‍👧‍👦'),
('Günlük tut', '📔'),
('Yatmadan önce telefonu bırak', '📱'),
('Esneme hareketleri yap', '🧘‍♀️'),
('Bir podcast dinle', '🎧'),
('Evde spor yap', '💪'),
('8 saat uyu', '😴'),
('Bir blog yazısı oku', '📱'),
('Çantanı düzenle', '👜'),
('Masanı temizle', '🧹'),
('Yeni bir tarif dene', '👩‍🍳'),
('Bir belgesel izle', '🎬'),
('Çiçek al', '🌸'),
('Yeni bir hobi edin', '🎨'),
('Bir yabancı dil çalış', '🗣️'),
('Bir bulmaca çöz', '🧩'),
('Bir müzeyi sanal tur ile gez', '🏛️'),
('Bir TED konuşması izle', '🎤'),
('Meditasyon yap', '🧘'),
('Bir online kurs izle', '💻'),
('Kütüphaneye git', '📚'),
('Bir resim çiz', '🎨'),
('Bir şiir oku', '📖'),
('Bir film izle', '🎬'),
('Bir arkadaşına hediye al', '🎁'),
('Bir yemek tarifi dene', '🥘'),
('Bir puzzle yap', '🧩'),
('Bir müzik aleti çal', '🎸'),
('Bir dans videosu izle', '💃'),
('Bir fotoğraf albümü düzenle', '📸'),
('Bir hayır işi yap', '🤝'),
('Bir ağaç dik', '🌳'),
('Bir kuşu besle', '🐦'),
('Bir sokak hayvanına yardım et', '🐱');

-- Yeni günün sözlerini ekle
INSERT INTO quotes (gununsozu, sozunsahibi) VALUES
('Hayat, cesur olanlara güzel sürprizler hazırlar.', 'Lewis Carroll'),
('Her yeni gün, yeni bir başlangıç şansıdır.', 'Dalai Lama'),
('Mutluluk paylaştıkça çoğalır.', 'Aristoteles'),
('Başarı, her gün küçük adımlar atmaktır.', 'Richard Branson'),
('En karanlık gece bile sonunda güneşe kavuşur.', 'Victor Hugo'),
('Hayallerinizin büyüklüğü, başarınızın sınırlarını belirler.', 'William Arthur Ward'),
('İyilik yapmak için yarını bekleme.', 'Mahatma Gandhi'),
('Her şeyin bir çözümü vardır, yeter ki inan.', 'Albert Einstein'),
('Kendine inanmak, başarının ilk adımıdır.', 'Ralph Waldo Emerson'),
('Bugün yaptığın seçimler, yarının hayatını belirler.', 'Eleanor Roosevelt'),
('Zorluklar, sizi güçlendiren fırsatlardır.', 'Dalai Lama'),
('Başarı bir yolculuktur, varış noktası değil.', 'Arthur Ashe'),
('En büyük hazine, sağlıklı bir zihindir.', 'Buddha'),
('Her başarısızlık, yeni bir başlangıç fırsatıdır.', 'Henry Ford'),
('Mutluluk, küçük şeylerde gizlidir.', 'Anne Frank'),
('Hayat, şu an yaşadığın andır.', 'Thich Nhat Hanh'),
('Değişim, içinde başlar.', 'Rumi'),
('Her gün yeni bir ders öğren.', 'Konfüçyüs'),
('Sevgi, en güçlü iyileştiricidir.', 'Hippokrates'),
('Başkalarına yardım et, kendini bulacaksın.', 'Mahatma Gandhi'),
('Hayat, dengede güzeldir.', 'Buddha'),
('Sabır, başarının anahtarıdır.', 'Bill Gates'),
('Kendini keşfetmek, en büyük yolculuktur.', 'Sokrates'),
('Umut, karanlıkta parlayan ışıktır.', 'Desmond Tutu'),
('Her yeni gün, yeni bir şans demektir.', 'Maya Angelou'),
('Başarı, hazırlık ile fırsatın buluşmasıdır.', 'Bobby Unser'),
('En iyi yatırım, kendine yapılan yatırımdır.', 'Benjamin Franklin'),
('Küçük adımlar, büyük değişimlerin başlangıcıdır.', 'Lao Tzu'),
('Sevgi, en güzel armağandır.', 'Mother Teresa'),
('Her zorluk, bir fırsattır.', 'Albert Einstein'),
('Bugünün hayalleri, yarının gerçekleridir.', 'Malcolm X'),
('Kendine iyi bak, her şey seninle başlar.', 'Oscar Wilde'),
('Yaşam, öğrenme sürecidir.', 'Aristoteles'),
('Her gülümseme, bir hediyedir.', 'Mother Teresa'),
('Başarı, vazgeçmemektir.', 'Winston Churchill'),
('İyilik bulaşıcıdır.', 'Desmond Tutu'),
('Zaman en değerli servettir.', 'Theophrastus'),
('Mutluluk bir tercihtir.', 'Dalai Lama'),
('Her son, yeni bir başlangıçtır.', 'Seneca'); 