INSERT INTO quotes (gununsozu, sozunsahibi) VALUES
('Başarı, her gün tekrarlanan küçük çabaların toplamıdır.', 'Robert Collier'),
('Yapamayacağını düşündüğün şey, seni yavaşlatan şeydir.', 'Tony Robbins'),
('Hiçbir şey imkansız değildir, kelimenin kendisi bile "Im possible" diyor.', 'Audrey Hepburn'),
('Bugün yaptığın seçimler, yarının hikayesini yazar.', 'Ralph Marston'),
('Hayal ettiğin her şey gerçek olabilir, yeter ki harekete geç.', 'Walt Disney'),
('Başarı yolculuğunda en önemli adım, başlamaya karar verdiğin andır.', 'Mark Twain'),
('Her başarısızlık, yeni bir başlangıç için bir fırsattır.', 'Henry Ford'),
('Kendine inan, gerisi kendiliğinden gelir.', 'Conor McGregor'),
('Zorluklar, güçlü insanlar yaratır.', 'Robert H. Schuller'),
('Yarın için endişelenmek yerine, bugün elinden geleni yap.', 'Dale Carnegie'),
('Başarı bir yolculuktur, varış noktası değil.', 'Arthur Ashe'),
('Her gün yeni bir başlangıçtır.', 'Buddha'),
('Düşlediğin hayatı yaşamak için, konfor alanından çıkmalısın.', 'Neale Donald Walsch'),
('Değişim kaçınılmazdır, gelişim bir seçimdir.', 'John Maxwell'),
('Küçük adımlar, büyük değişimlerin başlangıcıdır.', 'Chinese Proverb'),
('Başarı, vazgeçmediğin sürece imkansız değildir.', 'Winston Churchill'),
('Her şey zihinde başlar.', 'Buddha'),
('Hayallerinizin sınırı yoktur, sınırları koyan sizsiniz.', 'Unknown'),
('Bugün yapabileceğini yarına bırakma.', 'Benjamin Franklin'),
('Başarı, hazırlık ile fırsat buluştuğunda ortaya çıkar.', 'Zig Ziglar'),
('İnandığın yolda yürümekten korkma.', 'Ralph Waldo Emerson'),
('Her yeni gün, yeni bir başlangıç için bir fırsattır.', 'Mel Robbins'),
('Başarı için tek engel, kendi koyduğun sınırlardır.', 'Unknown'),
('Hayatta en büyük zafer, hiçbir zaman düşmemek değil, her düştüğünde ayağa kalkmaktır.', 'Nelson Mandela'),
('Değişimin ilk adımı, mümkün olduğuna inanmaktır.', 'Tony Robbins'); 