INSERT INTO tasks (taskname, taskicon) VALUES
('10 dakika meditasyon yap', '🧘‍♂️'),
('1 litre su iç', '💧'),
('10 dakika egzersiz yap', '🏃‍♂️'),
('Sevdiğin birine mesaj at', '💌'),
('Günün güzel anını not al', '📝'),
('Yeni bir şey öğren', '📚'),
('Odanı düzenle', '🧹'),
('Bir arkadaşını ara', '📞'),
('5 dakika nefes egzersizi', '🌬️'),
('Kendine bir iltifat et', '🌟'),
('Bir şey için teşekkür et', '🙏'),
('10 dakika kitap oku', '📖'),
('Bir iyilik yap', '❤️'),
('3 dakika dans et', '💃'),
('Günlük plan yap', '📅'),
('Yeni bir şarkı keşfet', '🎵'),
('5 dakika germe hareketi', '🤸‍♂️'),
('Bir hobine zaman ayır', '🎨'),
('Güzel bir fotoğraf çek', '📸'),
('Sağlıklı bir atıştırmalık ye', '🥗'),
('Pencereden manzarayı izle', '🪟'),
('3 dakika sessizce otur', '🧘'),
('Sevdiğin bir şarkıyı dinle', '🎧'),
('Bir hedef belirle', '🎯'),
('Derin bir nefes al', '🍃'); 